#!/bin/sh
 
USERNAME=$1
WATERMARK=$2

if [[ -z $USERNAME ]];
then
  echo "USAGE: tikdown [Username] (Optional) [Watermark {true | false}]"
  echo -e "\nExample: tikdown shenetworks"
  echo -e "Example: tikdown shenetworks true"
  echo "Invalid Input, Username Required"
  exit 1
fi


if [[ $WATERMARK == true ]];
then
  LINKS=$(curl -s https://proxitok.pussthecat.org/@$USERNAME | pup 'div.field p.control a.is-info attr{href}' | grep -E "/download" | sed 's/amp;//g')
else
  LINKS=$(curl -s https://proxitok.pussthecat.org/@$USERNAME | pup 'div.field p.control a.is-success attr{href}' | grep -E "/download" | sed 's/amp;//g')
fi

if ! [ -d $USERNAME ]; then
  mkdir $USERNAME
fi

echo -e "Downloading Started In Background\n"

COUNTER=1
for LINK in $LINKS;
do
  wget -q -t=2 -b https://proxitok.pussthecat.org/$LINK -O "$USERNAME/${COUNTER}.mp4"
  ((COUNTER++))
done

exit
